name: rakhsa
description: "Rakhsa"
publish_to: "none"

version: 2.0.0+19

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # A
  awesome_notifications: ^0.10.1

  # B
  badges: ^3.1.2

  # C
  camera: ^0.11.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1

  # D
  dio: ^5.9.0
  dartz: ^0.10.1
  device_info_plus: ^12.1.0

  # E
  equatable: ^2.0.7

  # F
  flutter_html: ^3.0.0
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.2
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.4
  flutter_widget_from_html: ^0.17.1
  flutter_background_service: ^5.1.0
  flutter_google_maps_webservices: ^1.1.1

  # Firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_crashlytics: ^5.0.3

  # Google
  googleapis: ^15.0.0
  google_api_headers: ^4.6.2
  google_maps_flutter: ^2.13.1

  # G
  get_it: ^8.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  gallery_saver_plus: ^3.2.9

  # H
  http: ^1.5.0

  # I
  intl: ^0.20.2
  image: ^4.5.4
  iconsax_plus: ^1.0.0
  image_picker: ^1.2.0

  # L
  location: ^8.0.1

  # N
  new_version_plus: ^0.1.1

  # S
  socket_io_client: ^3.1.2
  shared_preferences: ^2.5.3

  # P
  path: ^1.9.1
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  permission_handler: ^12.0.1

  # U
  uuid: ^4.5.1
  url_launcher: ^6.3.2

  # S
  shimmer: ^3.0.0

  # T
  tuple: ^2.0.2

  # V
  vibration: ^3.1.4

  # W
  weather: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/ppob/
    - assets/images/weather/
    - assets/images/update/
    - assets/sounds/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
