name: rakhsa
description: "Rakhsa"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # A
  # app_settings: ^6.1.1
  awesome_notifications: ^0.10.1

  # B
  badges: ^3.1.2
  barcode_widget: ^2.0.4

  # C
  camera: ^0.11.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  circular_countdown_timer: ^0.2.4
  cunning_document_scanner: ^1.3.1
  currency_text_input_formatter: ^2.3.0

  # D
  dio: ^5.9.0
  dartz: ^0.10.1
  dotted_line: ^3.2.3
  date_count_down: ^4.0.0
  device_info_plus: ^12.1.0

  # E
  equatable: ^2.0.7

  # F
  flutter_html: ^3.0.0
  flutter_spinkit: ^5.2.2
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1
  # fluttercontactpicker: ^4.7.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.4
  flutter_otp_text_field: ^1.5.1+1
  flutter_widget_from_html: ^0.17.1
  flutter_background_service: ^5.1.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_native_contact_picker: ^0.0.11
  flutter_google_maps_webservices: ^1.1.1

  # Firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3

  # Google
  googleapis: ^15.0.0
  # google_sign_in: ^7.2.0
  # googleapis_auth: ^2.0.0
  google_api_headers: ^4.6.2
  google_maps_flutter: ^2.13.1

  # G
  get_it: ^8.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  gallery_saver_plus: ^3.2.9

  # L
  # local_auth: ^3.0.0
  # lecle_flutter_absolute_path: ^0.0.2+1

  # I
  intl: ^0.20.2
  iconsax_plus: ^1.0.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0

  # M
  modal_progress_hud_nsn: ^0.5.1
  multi_image_picker_plus: ^0.0.7

  # N
  new_version_plus: ^0.1.1

  # S
  # soundpool: ^2.3.0
  socket_io_client: ^3.1.2
  shared_preferences: ^2.5.3
  syncfusion_flutter_barcodes: ^31.2.2
  # syncfusion_flutter_calendar: ^31.2.2

  # P
  provider: ^6.1.5+1
  permission_handler: ^12.0.1

  # R
  readmore: ^3.0.0

  # S
  sliding_up_panel: ^2.0.0+1

  # U
  uuid: ^4.5.1
  url_launcher: ^6.3.2

  # T
  tuple: ^2.0.2
  # timelines: ^0.1.0
  table_calendar: ^3.2.0
  # tflite_flutter: ^0.11.0

  # W
  weather: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/ppob/
    - assets/images/weather/
    - assets/images/update/
    - assets/sounds/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
