name: rakhsa
description: "Rakhsa"
publish_to: "none"

version: 2.4.0+29

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # A
  app_links: ^7.0.0
  awesome_notifications: ^0.10.1

  # B
  badges: ^3.1.2
  bounce: ^1.0.2

  # C
  camera: ^0.11.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1

  # D
  dio: ^5.9.0
  dartz: ^0.10.1
  device_info_plus: ^12.1.0

  # E
  equatable: ^2.0.7

  # F
  flutter_html: ^3.0.0
  fluttertoast: ^9.0.0
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_widget_from_html: ^0.17.1

  # Firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_remote_config: ^6.1.2

  # Google
  googleapis: ^15.0.0
  google_api_headers: ^4.6.2
  google_maps_flutter: ^2.13.1

  # G
  get_it: ^9.2.0
  geocoding: ^4.0.0
  go_router: ^17.0.0
  geolocator: ^14.0.2

  # I
  intl: ^0.20.2
  iconsax_plus: ^1.0.0
  image_picker: ^1.2.0

  # L
  lottie: ^3.3.2
  location: ^8.0.1

  # S
  socket_io_client: ^3.1.2
  shared_preferences: ^2.5.3

  # P
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.1
  pretty_dio_logger: ^1.4.0
  permission_handler: ^12.0.1
  play_install_referrer: ^0.5.0

  # U
  uuid: ^4.5.1
  upgrader: ^12.3.0
  url_launcher: ^6.3.2

  # S
  shimmer: ^3.0.0
  flutter_soloud: ^3.4.6

  # V
  vibration: ^3.1.4

  # W
  weather: ^3.2.1

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  go_router_builder: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/weather/

    # animations
    - assets/animations/

    # sound
    - assets/sound/

    # json
    - assets/json/

    # env
    - assets/env/.env.stag
    - assets/env/.env.prod

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
